name: Turrets
description: "A complex turret plugin that is WIP"
author: Legoboy
main: Legoboy\Turrets\TurretsPlugin
version: "0.1dev"
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
load: POSTWORLD